-- Project storage bootstrap for Market Intelligence Platform

CREATE DATABASE IF NOT EXISTS MARKET_INTELLIGENCE_DB;

CREATE SCHEMA IF NOT EXISTS MARKET_INTELLIGENCE_DB.CORE;
CREATE SCHEMA IF NOT EXISTS MARKET_INTELLIGENCE_DB.RAW;
CREATE SCHEMA IF NOT EXISTS MARKET_INTELLIGENCE_DB.STAGING;
CREATE SCHEMA IF NOT EXISTS MARKET_INTELLIGENCE_DB.MART;

CREATE STAGE IF NOT EXISTS MARKET_INTELLIGENCE_DB.RAW.GITHUB_STAGE;

CREATE TABLE IF NOT EXISTS MARKET_INTELLIGENCE_DB.CORE.PROJECT_RUN_AUDIT (
	RUN_ID STRING,
	SOURCE STRING,
	STATUS STRING,
	STARTED_AT TIMESTAMP_NTZ,
	FINISHED_AT TIMESTAMP_NTZ,
	MESSAGE STRING
);

CREATE TABLE IF NOT EXISTS MARKET_INTELLIGENCE_DB.RAW.GITHUB_REPOSITORY_SNAPSHOT (
	INGESTED_AT TIMESTAMP_NTZ,
	REPOSITORY_NAME STRING,
	DEFAULT_BRANCH STRING,
	VISIBILITY STRING,
	STARS NUMBER,
	FORKS NUMBER,
	OPEN_ISSUES NUMBER,
	RAW_PAYLOAD VARIANT
);

CREATE TABLE IF NOT EXISTS MARKET_INTELLIGENCE_DB.STAGING.REPOSITORY_DAILY_METRICS (
	METRIC_DATE DATE,
	REPOSITORY_NAME STRING,
	STARS NUMBER,
	FORKS NUMBER,
	OPEN_ISSUES NUMBER
);

CREATE TABLE IF NOT EXISTS MARKET_INTELLIGENCE_DB.MART.REPOSITORY_KPI (
	METRIC_DATE DATE,
	REPOSITORY_NAME STRING,
	POPULARITY_SCORE NUMBER(18,4),
	CHANGE_VS_PREV_DAY NUMBER(18,4)
);